### PR TITLE
Update Ground Facility visibility computation

### PR DESCRIPTION
**Pull request by mcontim**
Hi @ronisbr!

Following the Issue #4 , here a PR that attempts to solve the problem.

- I added the ECEF to ENU conversion in `is_ground_facility_visible` such to take into account the current ellispoid and the the Local Tangent Plane for that specific LAT-LON coordinate.
- The rotation matrix ECEF -> ENU, for each ground facility `vgs_rot_ecef_enu`, is pre-computed in `ground_facility_accesses` together with the ground facility ECEF vector `vgs_r_e` (already there). For doing this, I added a function `_rotmat_ecef_to_enu`.
- Alternatively, an internal function `ecef_to_ned`,together with a constant conversion matrix NED -> ENU could be used as shown in the alternative method for `is_ground_facility_visible`. However, this would bring to an overhead due to the computation of the same rotation matrix for each of the ground faciliies at each propagation step.
- I added a set of test to verify that the elevation with the new functions is properly computed.

Let me know what you think :)

### CODE REVIEW

**Comment by ronisbr** [comment]
Hi @BlueTeo91 !

Thank you very much for this PR!

Looking at your approach, I think we can improve it to avoid so many breaking changes.

The problem with the original algorithm, AFAIK, is because we are computing the local vertical wrong (the difference between the geocentric and geodetic latitudes). Hence, the elevation calculation is not very accurate considering the WGS-84 ellipsoid.

The simplest approach would be to create only a new signature of `is_ground_facility_visible` as follows:

```julia
is_ground_facility_visible(r_ned)
```

In this case, we restrict the satellite position to be represented in the NED reference frame of the ground station. Notice that we do not need the GF information here, because we will only check if the elevation is larger than `minimum_elevation`. In this reference frame, the local vertical has an elevation of 90°.

In the access and gap functions, we can use the function already defined in the SatelliteToolbox.jl ecosystem to transform the satellite position from the ECEF to the NED:

```
ecef_to_ned (with translate = true)
```

Afterwards, we only need to obtain the elevation and compare to the specification.

Am I missing something?

This proposed approach is better because it leads to a smaller number of modifications and introduce no breaking changes.

I also have some points to improve the PR:

1. Do not include the `Manifest.toml` file.
2. Do not include the `Project.toml` file in the `test/` directory.
3. Do not define functions inside the package that are used only for testing.
4. If possible, try obtaining a test set using another software.

**Comment by mcontim** [comment]
Hi @ronisbr!

Thank you for your comments.

The approach you are suggesting seems good and cleaner. In this way there is no need to add many changes and you can reuse functions already defined in `SatelliteToolbox.jl`
- Using `ecef_to_ned (with translate = true)` in `ground_facility_accesses `would replace the current computation of the ECEF -> ENU rotation matrix I added. 
- Then you can call the the new signature `is_ground_facility_visible(r_ned, minimum_elevation)` where you can check the visibility.

Thanks also for the suggestions for improving the PR, I didn't realize I was including the file you mentioned in point 1 and 2.
Regarding point 4, which other SW do you suggest? Some sample test from STK? I had a test against my packet initially but I removed to avoid another deps in the tests.

**Comment by ronisbr** [comment]
Perfect! Thanks!

> Regarding point 4, which other SW do you suggest? Some sample test from STK? I had a test against my packet initially but I removed to avoid another deps in the tests.

Anything you have! But skip it if it is difficult to obtain these values. We can add latter.

**Comment by mcontim** [comment]
Hi @ronisbr!

I added the signature `is_ground_facility_visible(r_ned, minimum_elevation)` and modified `ground_facility_accesses` accordingly.

- Now the rotations are not precomputed, as it was in the previous version of the PR, but `ecef_to_ned` is used instead, at each time step of the propagator. As said, this allow to fully reuse functions that are already part of `SatelliteToolbox.jl`.
- Now the tests still cover the check on the elevation as before. Furthermore, I added a specific scenario for which the issue was appearing (skipping the first short access). For the sake of completeness we could add further scenarios, maybe also using some outputs from STK, but if you agree we can add them later.
- The functions only used for test purposes are not part of the packet anymore but are inside `test/accesses_gaps.jl`.
- `Manifest.toml`, `test/Project.toml`, and `test/Manifest.toml` have been removed.

Let me know what you think :)

**Comment by ronisbr** [comment]
That's awesome @BlueTeo91 ! I just have few last comments:

1. Please, remove the `.gitignore` from the committed files.
2. For some reason, the commit deleted all png files from the documentation.
3. I think we can remove the function `_rotmat_ecef_to_enu`, right?

**Comment by ronisbr** [comment]
Ah! Please, do not remove the current signature of `is_ground_facility_visible` to avoid breaking changes.

**Comment by mcontim** [comment]
Hi @ronisbr!

Sorry, didn't realize I removed the .png in the documentation, now they should be back :)

- `.gitignore` has been removed.
- `_rotmat_ecef_to_enu` has been removed.
- The tests has been updated.
- The 2 orignal signature of  `is_ground_facility_visible` are kept to avoid breaking changes and a new one taking `r_ned` as input has been added. The current signatures are:
```julia
is_ground_facility_visible(sat_r_e::AbstractVector, gf_lat::Number, gf_lon::Number, gf_h::Number, θ::Number) -> Bool
is_ground_facility_visible(sat_r_e::AbstractVector, gf_r_e::AbstractVector, gf_rot_ecef_enu::SMatrix{3,3}, θ::Number) -> Bool
is_ground_facility_visible(sat_r_e::AbstractVector, gf_r_e::AbstractVector, θ::Number) -> Bool
```

Do I miss something? :)

**Comment by ronisbr** [comment]
Looks perfect! I will merge as soon the tests pass :) Thank you very much!

**Comment by ronisbr** [comment]
Done! Thank you very much @BlueTeo91 !

**Pull request merged**
